language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test
  - test $TRAVIS_RUST_VERSION != nightly || cargo test --no-default-features --features nightly
  - (cd libs/bragi && cargo test)
  - (cd libs/mimir && cargo test)
  - test $TRAVIS_RUST_VERSION != nightly || (cd libs/bragi && cargo test --no-default-features --features nightly)
  - test $TRAVIS_RUST_VERSION != nightly || (cd libs/mimir && cargo test --no-default-features --features nightly)

services:
  - docker
