language: rust
cache: cargo
before_script: 
  - cargo install -f rustfmt
  - export PATH=$PATH:$HOME/.cargo/bin
rust:
  - stable
  - beta
  - nightly
env:
  - NOTHING=INTERESTING
matrix:
  include:
    - rust: nightly
      env: RUSTFMT=YESPLEASE
      before_script: cargo install rustfmt-nightly --force
      script: cargo fmt --all -- --write-mode diff
  allow_failures:
    - rust: nightly
      env: NOTHING=INTERESTING

script:
  - cargo test --all

services:
  - docker
