language: rust
cache: cargo
before_script: 
  - cargo install -f rustfmt
  - export PATH=$PATH:$HOME/.cargo/bin
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo fmt -- --write-mode=diff
  - (cd libs/bragi && cargo fmt -- --write-mode=diff)
  - (cd libs/docker_wrapper && cargo fmt -- --write-mode=diff)
  - (cd libs/mimir && cargo fmt -- --write-mode=diff)
  - (cd libs/osm_builder && cargo fmt -- --write-mode=diff)
  - cargo test --all

services:
  - docker
