language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test --all
services:
  - docker
matrix:
  include:
    - rust: stable
      before_script: rustup component add rustfmt-preview
      script: cargo fmt --all -- --write-mode diff
  allow_failures:
    - rust: nightly
