language: rust
cache: cargo
rust:
  - stable
  - 1.36.0
env:
  - RUN=TEST
script:
  - cargo test --all
services:
  - docker
matrix:
  include:
    - rust: stable
      env: RUN=RUSTFMT
      before_script: rustup component add rustfmt
      script: cargo fmt --all -- --check
  allow_failures:
    - rust: nightly
