[package]
name = "mimirsbrunn"
version = "0.0.1"
authors = ["Canal TP <dt.ro@canaltp.fr>"]
build = "build.rs"

[dependencies]
log = "*"
env_logger = "*"
docopt = "*"
rustc-serialize = "*"
csv = "*"
curl = "*"
rs-es = "*"
serde = "*"
serde_json = "*"
regex = "*"
osmpbfreader = "*"

[dependencies.skojig]
path = "libs/skojig"

[dev-dependencies.docker_wrapper]
path = "libs/docker_wrapper"

[build-dependencies]
serde_codegen = "*"
syntex = "*"

# we just call one test method: cf. tests::all_tests()
[[test]]
name = "tests"
