[package]
name = "mimirsbrunn"
version = "0.0.1"
authors = ["Canal TP <dt.ro@canaltp.fr>"]
build = "build.rs"

[dependencies]
log = "*"
env_logger = "*"
docopt = "*"
rustc-serialize = "*"
csv = "*"
curl = "*"
rs-es = "*"
serde = "*"
serde_json = "*"
regex = "*"
osmpbfreader = "*"

[dependencies.skojig]
path = "libs/skojig"

[dev-dependencies.integration_tests]
path = "libs/integration_tests"

[build-dependencies]
serde_codegen = "*"
syntex = "*"
