[package]
name = "mimirsbrunn"
version = "0.0.1"
authors = ["Canal TP <dt.ro@canaltp.fr>"]
build = "build.rs"

[dependencies]
log = "*"
docopt = "*"
rustc-serialize = "*"
csv = "*"
curl = "*"
rs-es = { version = "0.3.4", default-features = false }
regex = "*"
osmpbfreader = "*"
chrono = "0.2"
serde = "*"

[dev-dependencies]
serde_json = "*"
hyper = "0.9.4"

[features]
default = ["rs-es/default", "skojig/default", "mimir/default"]
#nightly = ["skojig/nightly", "mimir/nightly"]

[dependencies.skojig]
path = "libs/skojig"
default-features = false

[dependencies.mimir]
path = "libs/mimir"
default-features = false

[dependencies.osm_builder]
path = "libs/osm_builder"
default-features = false

[dev-dependencies.docker_wrapper]
path = "libs/docker_wrapper"

# we just call one test method: cf. tests::all_tests()
[[test]]
name = "tests"
