[package]
name = "mimirsbrunn"
version = "1.21.0"
authors = ["Canal TP <dt.ro@canaltp.fr>"]
build = "build.rs"
autotests = false
edition = "2018"
description = "Set of tools for geocoding with Elasticsearch"
license = "AGPLv3"
repository = "https://github.com/CanalTP/mimirsbrunn.git"
keywords = [ "mimirsbrunn", "elasticsearch", "geocoding" ]
categories = [ "application" ]
readme = "README.md"

[workspace]
members = [
  "libs/mimir2",
  "libs/places"
]

[features]
db-storage = [ "rusqlite" ]

[dependencies]
config = "0.10"
log = { version = "0.4", features = ["release_max_level_debug"] }
slog = { version = "2.5", features = ["max_level_trace", "release_max_level_debug"]}
slog-scope = "4.3"
slog-envlogger = "2.2"
slog-async = "2.5"
slog-term = "2.8"
slog-stdlog = "4.1"
slog-json = "2.4"
structopt = "0.3"
futures = "0.3"
csv = "1.1"
csv-async = {version = "1.2", features = ["tokio", "with_serde"]}
rs-es = { git = "https://github.com/canaltp/rs-es", features = ["geo"], version = "0.12.3"}
regex = "1"
osmpbfreader = "0.14"
osm_boundaries_utils = "0.9"
chrono = "0.4"
chrono-tz = "0.5"
serde = {version = "1", features = ["rc"]}
serde_json = "1"
bincode = "1.2"
geo = "0.18"
geo-types = { version = "0.7", features = [ "rstar" ] }
rstar = "0.8"
itertools = "0.9"
transit_model = "0.31.4"
typed_index_collection = "1.1"
failure = "0.1"
cosmogony = "0.10"
par-map = "0.1.4"
lazy_static = "1.4"
num_cpus = "1.13"
assert_float_eq = "1.1"
human-sort = "0.2"
address-formatter = "0.2.1"
navitia-poi-model = "0.3"
walkdir = "2.3"
rusqlite = { version = "0.23", optional = true }
flate2 = { version = "1.0", features = [ "tokio" ] }
toml = "0.5"
tokio = { version = "1.6.0", features = [ "sync", "rt-multi-thread", "macros", "process" ] }
async-graphql = { version = "2.8", features = [ "chrono", "tracing" ] }
async-graphql-warp = "2.8"
snafu = { version = "0.6.10", features = [ "futures" ] }
clap = "2.33.1"
tracing = "0.1.26"
tracing-appender = "0.1.2"
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.17"
tracing-bunyan-formatter = { version = "0.2", default-features = false }
tracing-log = "0.1.2"
http = "0.2"
warp = { version = "0.3.1" }

mimir2 = { path = "libs/mimir2" }
places = { path = "libs/places" }

[lib]
name = "mimirsbrunn"
path = "src/lib.rs"

[dev-dependencies]
reqwest = { version = "0.11", features = [ "blocking", "json" ] }
env_logger = "*"
url = "2.2.2"
approx = "0.5"
actix-web = "1"
cucumber = { package = "cucumber_rust", version = "0.9" }
tokio = { version = "1.6.0", features = [ "rt-multi-thread", "macros", "process" ] }
elasticsearch = "7.12.0-alpha.1"

[build-dependencies]
json = "0.12"

[[bin]]
name = "b2"
path = "src/b2/main.rs"

[[test]]
name = "admin"
harness = false # Allows Cucumber to print output instead of libtest

# [[test]]
# name = "integration"
# harness = false # Allows Cucumber to print output instead of libtest

[patch.crates-io]
cosmogony = { git = "https://github.com/osm-without-borders/cosmogony", branch = "read-send-sync"}
