[package]
name = "mimirsbrunn"
version = "1.2.0"
authors = ["Canal TP <dt.ro@canaltp.fr>"]
build = "build.rs"

[workspace]

[dependencies]
log = "*"
docopt = "*"
rustc-serialize = "*"
csv = "*"
rs-es = "0.5"
regex = "*"
osmpbfreader = "*"
chrono = "0.2"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
geo = "^0.3"
gst = "0.1"
ordered-float = "0.0.2"
mdo = "*"
itertools = "*"

[dev-dependencies]
hyper = "^0.9"
iron-test = "*"
rustless = "*"
iron = "*"
mime = "0.2"

[dependencies.bragi]
path = "libs/bragi"

[dependencies.mimir]
path = "libs/mimir"

[dependencies.osm_builder]
path = "libs/osm_builder"

[dev-dependencies.docker_wrapper]
path = "libs/docker_wrapper"

# we just call one test method: cf. tests::all_tests()
[[test]]
name = "tests"
