[package]
name = "mimirsbrunn"
version = "1.2.0"
authors = ["Canal TP <dt.ro@canaltp.fr>"]
build = "build.rs"
autotests = false
edition = "2018"

[workspace]

[dependencies]
log = { version = "0.4", features = ["release_max_level_debug"] }
slog = { version = "2.1", features = ["max_level_trace", "release_max_level_debug"]}
slog-scope = "4.0"
slog-envlogger = "2.1.0"
slog-async = "2.2.0"
structopt = "0.2"
csv = "1.0.0-beta.4"
rs-es = {version = "0.10.5", default-features = false}
regex = "*"
osmpbfreader = "0.11.2"
chrono = "0.4"
serde = {version = "1", features = ["rc"]}
serde_derive = "1"
serde_json = "1"
geo = "0.10"
geo-types = "0.2.0"
gst = "0.1"
ordered-float = "0.0.2"
itertools = "*"
navitia_model = { git = "https://github.com/CanalTP/navitia_model" }
osm_boundaries_utils = "0.3"
failure = "0.1"
cosmogony = "^0.4.1"
par-map = "0.1.4"
lazy_static = "1.1.0"
num_cpus = "1.8.0"
assert_float_eq = "1"

[dev-dependencies]
hyper = "0.10"
approx = "0.2.0"
actix-web = "0.7"

[build-dependencies]
git-version = "0.2"

[dependencies.bragi]
path = "libs/bragi"

[dependencies.mimir]
path = "libs/mimir"

[dev-dependencies.docker_wrapper]
path = "libs/docker_wrapper"

# we just call one test method: cf. tests::all_tests()
[[test]]
name = "tests"
