[package]
name = "mimirsbrunn"
version = "1.2.0"
authors = ["Canal TP <dt.ro@canaltp.fr>"]
build = "build.rs"

[workspace]

[dependencies]
log = "*"
docopt = "0.8"
csv = "1.0.0-beta.4"
rs-es = {version = "0.10", default-features = false}
regex = "*"
osmpbfreader = "*"
chrono = "0.4"
serde = {version = "1", features = ["rc"]}
serde_derive = "1"
serde_json = "1"
geo = "0.4.7"
gst = "0.1"
ordered-float = "0.0.2"
mdo = "*"
itertools = "*"

[dev-dependencies]
hyper = "0.10"
iron-test = "0.4"
rustless = "*"
iron = "0.4"
mime = "0.2"

[dependencies.bragi]
path = "libs/bragi"

[dependencies.mimir]
path = "libs/mimir"

[dependencies.osm_builder]
path = "libs/osm_builder"

[dev-dependencies.docker_wrapper]
path = "libs/docker_wrapper"

# we just call one test method: cf. tests::all_tests()
[[test]]
name = "tests"

[replace]
# remove this line once queryst > 1.0.1 is released
"queryst:1.0.1" = { git = "https://github.com/rustless/queryst", rev = "b29604af7bfb05c2b9d98d726ab1bafd0533cc10" }
