[package]
name = "mimirsbrunn"
version = "1.2.0"
authors = ["Canal TP <dt.ro@canaltp.fr>"]
build = "build.rs"

[dependencies]
log = "*"
docopt = "*"
rustc-serialize = "*"
csv = "*"
rs-es = { version = "^0.4.4", default-features = false }
regex = "*"
osmpbfreader = "*"
chrono = "0.2"
serde = "^0.7.10"
geo = "0.1.1"
gst = "0.1"
ordered-float = "0.0.2"
mdo = "*"

[dev-dependencies]
serde_json = "*"
hyper = "^0.9"
iron-test = "0.3.0"
rustless = "*"
iron = "*"
mime = "0.2"

[features]
default = ["rs-es/default", "bragi/default", "mimir/default"]
#nightly = ["bragi/nightly", "mimir/nightly"]

[dependencies.bragi]
path = "libs/bragi"
default-features = false

[dependencies.mimir]
path = "libs/mimir"
default-features = false

[dependencies.osm_builder]
path = "libs/osm_builder"
default-features = false

[dev-dependencies.docker_wrapper]
path = "libs/docker_wrapper"

# we just call one test method: cf. tests::all_tests()
[[test]]
name = "tests"
