[street]

  [street.exclusion]

  # See [OSM Key Highway](https://wiki.openstreetmap.org/wiki/Key:highway) for background.
  highways = [
    "bus_guideway",
    "bus_stop",
    "elevator",
    "escape",
    "platform"
  ]
