name: Create and publish bargi docker image

on:
  push:
    branches:
      - master
      - release
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: create publish ${{ env.BRANCH_NAME }} images
        run: |
          make docker-build-bragi-${{ env.BRANCH_NAME }} DEBIAN_VERSION=buster RUST_VERSION=1.44.1
          make dockerhub-login DOCKER_USER=${{secrets.docker_user}} DOCKER_PASSWORD=${{secrets.docker_password}}
          make push-bragi-image-${{ env.BRANCH_NAME }}

      - name: Remove all useless images
        run: make wipe-useless-images
