name: Packages

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: jessie
            packages: pkg-config libssl-dev
            rust: 1.44.1
          - version: stretch
            packages: pkg-config libssl1.0-dev
            rust: 1.44.1
          - version: buster
            packages: pkg-config libssl-dev
            rust: 1.48.0

    container: debian:${{matrix.version}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          apt-get update
          apt-get install -y curl wget build-essential
          apt-get install -y ${{ matrix.packages }}
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - name: Validate Code
        if: ${{matrix.version == 'buster' }}
        run: make check
      - name: Build package
        run: ./scripts/build_deb.sh ${{ matrix.version }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debian-package
          path: ./scripts/deb-scratch/*
